module.exports = {
    '/siteconfig': require('../api/SiteconfigApi'),
    '/business': require('../api/BusinessApi'),
    '/organization': require('../api/OrganizationApi'),
    
    '/countries': require('../api/CountriesApi'),
    '/states': require('../api/StatesApi'),
    '/countryall': require('../api/CountryallApi'),
    '/stateall': require('../api/StateallApi'),
    '/cityall': require('../api/CityallApi'),
    '/city': require('../api/CityApi'),
    '/geo': require('../api/GeoApi'),
    '/siteaccount': require('../api/AclassApi'),
    '/sitetime': require('../api/TimeApi'),
    '/client': require('../api/ClientApi'), 
    '/timeall': require('../api/TimeallApi'),
    '/leavemanagementopts': require('../api/leaveManOptsAPi'),
    '/employeetabopt': require('../api/employeeTabApi'),
    '/createemployee': require('../api/CreateEmployeeApi'),
    '/businessunit': require('../api/BusinessunitApi'), 
    '/departments': require('../api/DepartmentsApi'),
    '/defaulttask': require('../api/DefaultTaskApi'), 
    '/appraisal': require('../api/AppraisalApi'),
    '/configuration': require('../api/ConfigurationApi'),
    '/payfrequency': require('../api/PayfrequencyApi'), 
    '/jobtitle': require('../api/JobtitleApi'),  
    '/position': require('../api/PositionApi'),
    '/employmentstatus': require('../api/EmploymentstatusApi'), 
    '/disability': require('../api/DisabilityApi'), 
    '/general': require('../api/GeneralApi'), 
    '/emp_documenttype': require('../api/Emp_documenttypeApi'),
    '/timesheet': require('../api/TimesheetApi'),
    '/rolesprivileges': require('../api/RolesPrivilegesApi'),
    '/frequenttask': require('../api/FrequenttaskApi'),
    '/project_time': require('../api/ProjecttimeApi'),
    '/projects': require('../api/ProjectApi'),
    '/fsfiles': require('../api/FsFilesApi'),
    '/usergenerate': require('../api/UserGenerateApi'),   
    '/management': require('../api/ManagementApi'),
    '/employeeconfiguration': require('../api/EmployeeconfigurationApi'),
    '/exitprocedure': require('../api/ExitprocedureApi'),
    '/contacts': require('../api/ContactsApi'),
    '/organizations': require('../api/OrganizationsApi'),
    '/selfservice': require('../api/SelfServiceApi'),
    '/user': require('../api/UserApi'),
    '/category': require('../api/categoryApi'),
    '/pmode': require('../api/pmodeApi'),
    '/asset': require('../api/AssetApi'),
    '/disciplinary': require('../api/Disciplinary'),
    '/expense': require('../api/ExpenseApi'),
    '/recruitment': require('../api/RecruitmentApi')
    
    
}