module.exports = {
	siteconfig:require('./siteconfig.js'),
	business:require('./business.js'),
	organization:require('./organization.js'),

  countries:require('./countries.js'),
  states:require('./states.js'),
  countryall:require('./countryall.js'),
  stateall:require('./stateall.js'),
  cityall:require('./cityall.js'),
  city:require('./city.js'),
	geo:require('./geo.js'),
  siteaccount:require('./siteaccount.js'),
  sitetime:require('./sitetime.js'),
  timeall:require('./sitetimeall.js'),
  client:require('./client.js'),
  general:require('./general.js'),
  leavemanagementopts:require('./leaveManagementOpts.js'),
  employeetab:require('./employeetab.js'),
  createemployee:require('./createemployee.js'),
  businessunit:require('./businessunit.js'),
  departments:require('./departments.js'),
  defaulttask:require('./defaulttask.js'),
  configuration:require('./configuration.js'),
  payfrequency:require('./payfrequency.js'),
  jobtitle:require('./jobtitle.js'),
  position:require('./position.js'),
  employmentstatus:require('./employmentstatus.js'),
  disability:require('./disability.js'),
  emp_documenttype:require('./emp_documenttype.js'),
  timesheet:require('./timesheet.js'),
  rolesprivileges:require('./rolesprivileges.js'),
  project_time:require('./projecttime.js'),
  frequenttask:require('./frequenttask.js'),
  projects:require('./projects.js'),
  fsfiles:require('./fsfiles.js'),
  usergenerate:require('./userGenerate.js'),
  management: require('./management.js'),
  exitprocedure: require('./exitprocedure.js'),
  contacts: require('./contacts.js'),
  appraisal: require('./appraisal.js'),
  organizations: require('./organizations.js'),
  employeeconfiguration: require('./employeeconfiguration.js'),
  selfservice: require('./selfservice.js'),
  User:require('./user.js'),    
  category: require('./category.js'),
  pmode: require('./pmode.js'),
  asset: require('./asset.js'),
  disciplinary: require('./disciplinary.js'),
expense: require('./expense.js'),
recruitment: require('./recruitment.js'),
domain:require('./domain.js')
};